# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Help for the USAJOBS Agency Talent Portal
email: matthew.dingee@opm.gov
description: Get help with strategic recruitment.
logo: "/assets/images/logo-2x.png"
url: "http://usajobs.github.io/ATP-Support/" # the base hostname & protocol for your site
baseurl: "/ATP-Support"

exclude:
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - package.json
  - package-lock.json
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md
  - ".sass-cache"
  - ".ruby-version"
  - npm-debug.log
  - node_modules

destination: ./_dist

author:
  name: USAJOBS
  url: https://usajobs.github.io/

repository:
  name: ATP-Support
  url: https://github.com/USAJOBS/ATP-Support/

# Google Analytics
analytics_id: "UA-33523145-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

collections:
  pages:
    output: true
    permalink: /:path/
